### ISSUE TITLE
Start App

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#1]
### Value Statement
As a user I want to enter the App so that I can find information about a sustainable life in hamburg.

### Description
![Bildschirmfoto 2022-01-05 um 14 15 31](https://user-images.githubusercontent.com/93935995/148223865-21376d01-1c0d-44b4-b1f6-71e9b3dcf8d7.png)

### Acceptance Criteria
- user opens the web app and enters first screen

### Complexity
- L

### Tasks
- [x] create feature-branch
- [x] SetUp React Project (Folder, Files, first component)
- [x] Create GlobalStyles and basic styling
