### ISSUE TITLE
add a new restaurant, shop, beauty salon to the list

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#11]
### Value Statement
As a user I of this app I want to add other Restaurants, Shops, beauty salons etc. so that I can also find these ones here in this app.

### Description
![Bildschirmfoto 2022-01-05 um 17 47 11](https://user-images.githubusercontent.com/93935995/148255888-f8f6745a-f80f-4429-81bb-22f2f33cff10.png)

### Acceptance Criteria
- user can add information of the respective restaurant, shop beauty salon etc. with the inputfields
- with click on "hinzufügen" he adds a new card to the other cards

### Complexity
L

### Tasks
- [ ] create new feature-branch "add-cards"
- [ ] create component with input-fields
- [ ] import component in other components
- [ ] create connection between this component and the respective main-section (restaurant, shop, beauty..)
- [ ] add routing
- [ ] add styling
