### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#12]
### Value Statement
As a user I want to see the Header of the respective page so that I know where I exactly am in the App.

### Description
ONLY HEADER
![Bildschirmfoto 2022-01-05 um 14 15 41](https://user-images.githubusercontent.com/93935995/148230245-41403870-5c79-4767-952e-cb16427f1180.png)

### Acceptance Criteria
- click on the respective nav-icon leads the user to a sub-page
- user sees headline/ header on every page to know where he/ she is

### Complexity
S

### Tasks
- [x] create new feature-branch "Header"
- [x] import component in every sub-page
- [x] add appropriate icons (?)
- [x] add routing
- [x] add styling
