### ISSUE TITLE
Favourite Button

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#17]
### Value Statement
As a user I want to add cards to my favourites-section so that I can see all my favourite restaurants, shops, beauty-spots in one menu-point. 

### Description
![Bildschirmfoto 2022-01-05 um 14 15 41](https://user-images.githubusercontent.com/93935995/148230245-41403870-5c79-4767-952e-cb16427f1180.png)

### Acceptance Criteria
- click on the heart-icon adds the card to the favourite-section

### Complexity
S

### Tasks
- [x] create new feature-branch "favourite-button"
- [x] import component in Information-Card
- [x] add usestate for favourites
- [x] add appropriate icons 
- [x] add styling
