### ISSUE TITLE
Toggle Button for detailed information

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#18]
### Value Statement
As a user I want to see detailed information about vegetarian & vegan restaurants, about sustainable shops and beauty salons/ hairdresser so that I know where they are exactly and how I can reach them. 

### Description
![Bildschirmfoto 2022-01-05 um 14 15 48](https://user-images.githubusercontent.com/93935995/149297720-db48ac9c-ecc7-4a6d-a376-9885052b5824.png)

### Acceptance Criteria
- click on the "Mehr Informationen"-Button shows the user detailed information to the respective card
- user can see a map-snippet

### Complexity
L

### Tasks
- [x] create new feature-branch "toggle-button"
- [x] create toggle-button component
- [x] import component to the information-cards
- [x] add routing
- [x] add styling
