### ISSUE TITLE
Enter main menu

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#2]
### Value Statement
As a user I want to enter the main menu so that I can get an overview about the functions in this app and to start the navigation. 

### Description
![Bildschirmfoto 2022-01-10 um 14 25 19](https://user-images.githubusercontent.com/93935995/148773366-2abb3870-163f-406f-acdc-eb9ed9e5dba9.png)

### Acceptance Criteria
- user has opened the app and sees main menu after the greeting-screen ("Willkommen bei nacHHaltig...")
- user can reach a specific page by clicking on the respective menu-point 

### Complexity
- M

### Tasks
- [x] create feature-branch
- [x] create main menu component
- [x] set routes to the respective pages
- [x] add styling
