### ISSUE TITLE
Modal / Pop-Up

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#22]
### Value Statement
As a user I want to know what kind of information I can expect on every page so that I know if I want to stay on the page or not. 

### Description
<img width="320" alt="Bildschirmfoto 2022-01-17 um 17 07 36" src="https://user-images.githubusercontent.com/93935995/149804017-b7bcb617-cc65-4979-af4e-c4b36c3c5637.png">

### Acceptance Criteria
- click on the Modal Button opens new window/ layer
- user can read information

### Complexity
S

### Tasks
- [x] create new feature-branch "Modal"
- [x] create Modal component
- [x] import component in respective pages
- [x] add usestate to toggle Modal
- [x] add styling
