### ISSUE TITLE
Footer-Navigation

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#3]
### Value Statement
As a user I want to reach every page in the app with the footer-navigation-bar so that I can reach the page I want anytime.

### Description
![Bildschirmfoto 2022-01-05 um 14 46 39](https://user-images.githubusercontent.com/93935995/148227689-c68aa82c-eac6-4f93-8e86-9f2a1278bc68.png)

### Acceptance Criteria
- click on the respective icon guides the user to the respective page
- user can reach every page  anytime regardless of which page the user is currently on

### Complexity
M

### Tasks
- [x] create new feature-branch "navbar"
- [x] create footer-navbar component
- [x] import component in respective pages
- [x] add appropriate icons 
- [x] add routing
- [x] add styling
