### ISSUE TITLE
Get Basic-Information about restaurants, shops, beauty spots

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#4]
### Value Statement
As a user I want to get basic information about vegetarian & vegan restaurants, about sustainable shops and beauty salons/ hairdresser so that I can decide which spot I want to visit. 

### Description
![Bildschirmfoto 2022-01-05 um 14 15 41](https://user-images.githubusercontent.com/93935995/148230245-41403870-5c79-4767-952e-cb16427f1180.png)

![Bildschirmfoto 2022-01-05 um 14 15 56](https://user-images.githubusercontent.com/93935995/148230287-b61300d0-239b-4571-a15b-92bbd0d0aff7.png)

![Bildschirmfoto 2022-01-05 um 14 16 00](https://user-images.githubusercontent.com/93935995/148230302-a4dc2aec-fa14-4bba-b7ce-41db87c907bd.png)

### Acceptance Criteria
- user can see basic information in alle three menu-points (restaurants, shops, beauty)
- user can see a map-snippet

### Complexity
L

### Tasks
- [x] create new feature-branch "information-cards"
- [x] create Basic-Card component
- [x] import component to the pages
- [x] add routing
- [x] add styling
