### ISSUE TITLE
Filter Opportunity

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#5]
### Value Statement
As a user I want to filter information about vegetarian & vegan restaurants, about sustainable shops and beauty salons/ hairdresser so that I can find e.g. a specific restaurant I want to visit.   

### Description
![Bildschirmfoto 2022-01-05 um 15 37 37](https://user-images.githubusercontent.com/93935995/148235618-f7acc933-ff60-4f2c-b5f3-9481a270b89b.png)

### Acceptance Criteria
- click on the filter-button gives user different options to filter cards
- user can scroll up and down

### Complexity
L

### Tasks
- [x] create new feature-branch "Filter-Button"
- [x] import component in information-Card component
- [x] add usestate for filtered results
- [x] add styling
