### ISSUE TITLE
Get detailed information about restaurants, shops, beautysalons/hairdressers

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#6]
### Value Statement
As a user I want to get detailed information about vegetarian & vegan restaurants, about sustainable shops and beauty salons/ hairdresser so that I know where these are exactly and how I can reach them.   

### Description
![Bildschirmfoto 2022-01-05 um 14 15 48](https://user-images.githubusercontent.com/93935995/148237846-924ad6aa-a5a7-4399-afcf-472a7fc6bb50.png)

### Acceptance Criteria
- click on the "Mehr Informationen"-Button shows the user detailed informationen to the respective card
- user can see a map-snippet 
- user can go back with click on "zurück-button" to see the overview of all cards

### Complexity
L

### Tasks
- [ ] create new feature-branch "Detailed-Cards"
- [ ] create component
- [ ] import component in Basic-Card.jsx
- [ ] add "zurück-button"
- [ ] add routing
- [ ] add styling
