### ISSUE TITLE
See (on a map) where the restaurant/shop/beautysalon is located

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#8]
### Value Statement
As a user I want to see (on a map) where the restaurant/ shop is located exactly so that I know how I can reach it.

### Description
![Bildschirmfoto 2022-01-05 um 14 15 48](https://user-images.githubusercontent.com/93935995/149297720-db48ac9c-ecc7-4a6d-a376-9885052b5824.png)

### Acceptance Criteria
- click on the "Mehr Informationen"-Button shows the user detailed information to the respective card
- user can see a map-snippet

### Complexity
L

### Tasks
- [x] create new feature-branch "map-function"
- [x] create map-function component
- [x] import component to the information-cards
- [x] add marks depending on address 
- [x] add styling
