### ISSUE TITLE
calculate Co2-emission for car ride/ train ride/ flight

### ISSUE THREAD

**Issue by danielab93** [danielab93/capstone-project#9]
### Value Statement
As a user I of this app I want to calculate my Co2-footprint for car- &  train-rides any for flights. I want to save it with a formular so that I have an overview of all my co2-emissions.

### Description
<img width="209" alt="Bildschirmfoto 2022-01-05 um 16 51 09" src="https://user-images.githubusercontent.com/93935995/148247365-1eed0b35-f1f1-46e9-a9de-ab6c045d52aa.png">

### Acceptance Criteria
- click on the last symbol right in the footer-navbar leads the user to the co2-calculator
- user can enter kilometers he/ she traveled by car, train or airplane
- with click on "Hinzufügen" the feature calculates the co2-emission and adds it to the overview

### Complexity
L

### Tasks
- [x] create new feature-branch "Co2-Calculator"
- [x] create component
- [x] import component in MainMenu
- [x] add general calculate-function
- [x] add localstorage
- [x] add styling
